### PR TITLE
remove some unused imports

### PR DESCRIPTION
**Pull request by fchapoton**
as suggested by lgtm

https://lgtm.com/projects/g/yaml/pyyaml/

### CODE REVIEW

**Comment by fchapoton** [comment]
anybody listening ?

**Comment by perlpunk** [comment]
I think `sys` can also be removed from `lib3/yaml/representer.py`.
Could you add that and rebase to master? Then we might get it into v5.3

**Comment by hSaria** [comment]
You can also remove `from distutils.dir_util import mkpath` from `setup.py`.

**Comment by fchapoton** [comment]
removed

**Comment by perlpunk** [comment]
Thanks, merged!

**Comment by perlpunk** [comment]
released https://pypi.org/project/PyYAML/5.3/

**Pull request merged**
