### PR TITLE
Change default Loader for add_constructor to FullLoader

### LINKED ISSUE #271: convenience methods in __init__.py should modify FullLoader instead of Loader
For example `add_constructor()` in 5.1 is a no-op for legacy code since it adds the constructor to Loader but FullLoader is the one used in load(input).

https://github.com/yaml/pyyaml/blob/master/lib3/yaml/__init__.py#L329-L344

### PR DESCRIPTION
**Pull request by perlpunk**
Fixes #271

### CODE REVIEW

**Comment by samueljsb** [comment]
Is this going to be included in the next release?

**Comment by perlpunk** [comment]
I think @ingydotnet wants to release #287 instead

**Comment by samueljsb** [comment]
Oh perfect, that also solves my problem!

**Comment by perlpunk** [comment]
Closing, replaced by #287

**Pull request closed without merging**
