### PR TITLE
ARM64: Add ARM64 jobs in Travis-CI

### PR DESCRIPTION
**Pull request by ossdev07**
Travis-CI has added support for ARM64. Added ARM64 jobs in Travis-CI.

### CODE REVIEW

**Comment by perlpunk** [comment]
Thanks! Could you rebase to current master? There were some new tests added.

**Comment by ossdev07** [comment]
Ping @perlpunk I have rebased to current master, can you please have a look.

**Comment by ossdev07** [comment]
Hi @perlpunk ,

I have rebased to current master and added commit. Please check and provide feedback.

**Comment by qa8302** [comment]
USE Order

**Pull request merged**
