### PR TITLE
Use `is` instead of equality for comparing with `None`

### PR DESCRIPTION
**Pull request by GeyseR**

### CODE REVIEW

**Comment by Matthew-Reynolds** [comment]
For some more context on why this is a good change, from [PEP 8](https://www.python.org/dev/peps/pep-0008/):
>Comparisons to singletons like None should always be done with is or is not, never the equality operators.

And a related [StackOverflow](https://stackoverflow.com/questions/3257919/what-is-the-difference-between-is-none-and-none/) question explaining why this convention is preferable.

**Comment by 4383** [comment]
> For some more context on why this is a good change, from [PEP 8](https://www.python.org/dev/peps/pep-0008/):
> 
> > Comparisons to singletons like None should always be done with is or is not, never the equality operators.
> 
> And a related [StackOverflow](https://stackoverflow.com/questions/3257919/what-is-the-difference-between-is-none-and-none/) question explaining why this convention is preferable.

https://www.python.org/dev/peps/pep-0008/#id51

**Comment by perlpunk** [comment]
I wasn't able to correctly rebased, so I cherry-picked the commit. Thanks!

**Comment by perlpunk** [comment]
released https://pypi.org/project/PyYAML/5.3/

**Pull request closed without merging**
