### PR TITLE
Allow to turn off sorting keys in Dumper

### PR DESCRIPTION
**Pull request by perlpunk**
See issue #110

This allows to do:

    output = yaml.dump(data, sort_keys=False)

The default is True because of backwards compatibility.

This can be useful for python >= 3.7 to preserve key order. Also not sorting will probably be faster.

I didn't add a test because I'm not yet familiar with testing in python
and couldn't find out how the pyyaml test suite works.

Also i don't know where to document that.

### CODE REVIEW

**Comment by perlpunk** [comment]
Travis tests are failing. I need to find out how to run the tests locally. Any hints for a python beginner?

**Comment by perlpunk** [comment]
thanks @ingydotnet for `python setup.py test`
I pushed a fix for `cyaml.py`, tests are passing now for python > 2.6

**Comment by perlpunk** [comment]
I started to write a test for this. Will probably push it tomorrow

**Comment by perlpunk** [comment]
rebased to master, tests now including 3.7-dev, and 2.6 is passing

**Comment by perlpunk** [comment]
Rebased to current master, squashed commits.
Tests are passing (and now include the libyaml tests also)

**Comment by dsposito** [comment]
This is great! Looking forward to this being merged! 🚀

**Comment by dsposito** [comment]
@jasonrhaas I'm hoping this eventually gets merged to source but for now [oyaml](https://github.com/wimglenn/oyaml) does the trick.

**Comment by dilumr** [comment]
I too am interested is this. Would like to use in a feature where a tool slightly modifies YAML files that are checked into source. Would love the edits to look slight. The YAML files are initially ordered by hand, to expecting keys to be alphanumerically sorted is unrealistic; humans tend to group keys by purpose and/or importance.

**Comment by gatopeich** [comment]
Dear Perl punk, this is not an acceptable solution.

Sorting the keys was a needless change seemingly made while playing alone (learning python?) on a dormant project. It is anti-pythonic, anti-yaml, and goes against the most basic principle of not doing needless things.

Now it is obvious from the comments that devs using PyYAML for actual work are not agreeing with your change. Like in my case, it renders this library unusable for their projects.

*Whoever wants the keys sorted should be doing it at the .yaml source. That is the whole point of defining interfaces in YAML.*

Besides, I don't believe in the "backwards compatibility" excuse. Could you point us to a project that would be negatively affected by removing this anti-feature?

Please listen to the community and be honest here.

**Comment by gatopeich** [comment]
> 
Would it make sense to make the default depend on the python version?

Okay. Then let's apply same default as for `json.dumps()`: sort_keys=True until Python 2.6, False since v2.7.

**Comment by ofek** [comment]
Can this be merged now?

**Comment by perlpunk** [comment]
Closing, recreated based on current master: #254

**Pull request closed without merging**
