### PR TITLE
Parse datetime timezone

### PR DESCRIPTION
**Pull request by luiscoms**
Add timezone when parse datetime

When I load an yaml like `yaml.load("2018-02-11 19:00:00-02:00")`

I got
> 2018-02-11 21:00:00

Instead of
> 2018-02-11 19:00:00-02:00

### CODE REVIEW

**Comment by luiscoms** [comment]
Any reviews on this PR?

**Comment by ingydotnet** [comment]
@luiscoms After the 5.1 release, I expect to review this PR (and many others) for the next release.

Thank you for the work.

**Comment by seansfkelley** [comment]
See also $#163. I prefer the code style in this PR, but #163 uses standard library timezone objects when available, which seems preferable.

**Comment by luiscoms** [comment]
Here is user datetime.timezone to parsing timezone https://github.com/yaml/pyyaml/pull/251/files#diff-a5f8b847ff620043866fa0e0d854af0dR334

**Comment by mattseymour** [comment]
Is there an ETA on supporting TZ date times. Currently [163](https://github.com/yaml/pyyaml/pull/163), [113](https://github.com/yaml/pyyaml/pull/113) and [251](https://github.com/yaml/pyyaml/pull/251) are all open which try to resolve this issue. It seems to be an issue being faced by a lot of people and the fact 3 pull requests are open for such an issue highlights this.

It would be good if someone from the core team could shed some light on why these changes have taken a while to get reviewed so we may assist where possible; whether it is that the devs are busy or have reservations about the PR's. In either case, it would be good to start a conversation around this so we can all contribute to help push this change into master (sooner rather than later). 

_Cross-posting to other tickets._

**Comment by perlpunk** [comment]
> See also #163. I prefer the code style in this PR, but #163 uses standard library timezone objects when available, which seems preferable.

Could you explain the difference to #163? I'm still new to python.

**Comment by seansfkelley** [comment]
https://github.com/yaml/pyyaml/pull/163/files#diff-cf4d4f120c4c496f37b4d3d84f585b46R357-R363 is not very DRY.

https://github.com/yaml/pyyaml/pull/251/files#diff-cf4d4f120c4c496f37b4d3d84f585b46R348 seems preferable.

The two PRs seem to have converged a bit in order to support Python 2. When I said it uses "standard library time zones", I meant that it didn't implement its own class, which it now does as of https://github.com/yaml/pyyaml/pull/163/commits/12d5efd10ddf6c5650230f67b8f49578942e7b34. Also, the implementations of `timezone` are currently different between these two PRs. It's been a while since I've looked at time zone stuff in Python, but not wrapping standard library things seems better from a compatibility perspective too (I've had issues mixing zone objects from different libraries that should have been interchangeable, but were not).

**Comment by perlpunk** [comment]
Thanks. I would like to get this in the next release, but won't have much time until next weekend.

**Comment by perlpunk** [comment]
I merged #163 
I also created #363 to add timezone tests. Maybe you could have a look if it makes sense?

**Comment by perlpunk** [comment]
released https://pypi.org/project/PyYAML/5.3/

**Pull request closed without merging**
