### PR TITLE
fix yaml construct a slot object

### PR DESCRIPTION
**Pull request by Hanaasagi**
Env:
- Python 3.7
- pyyaml master branch

Test code:

```Python
import yaml


class A:
    __slots__ = ('c',)

    def __init__(self):
        self.c = 3


data = yaml.dump({'a': A()})
d = yaml.load(data)
```

Trackback:

```
Traceback (most recent call last):
  File "t.py", line 12, in <module>
    d = yaml.load(data)
  File "/root/py36/lib/python3.7/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/root/py36/lib/python3.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/root/py36/lib/python3.7/site-packages/yaml/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/root/py36/lib/python3.7/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/root/py36/lib/python3.7/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/root/py36/lib/python3.7/site-packages/yaml/constructor.py", line 129, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/root/py36/lib/python3.7/site-packages/yaml/constructor.py", line 88, in construct_object
    data = constructor(self, tag_suffix, node)
  File "/root/py36/lib/python3.7/site-packages/yaml/constructor.py", line 617, in construct_python_object_new
    return self.construct_python_object_apply(suffix, node, newobj=True)
  File "/root/py36/lib/python3.7/site-packages/yaml/constructor.py", line 608, in construct_python_object_apply
    self.set_python_instance_state(instance, state)
  File "/root/py36/lib/python3.7/site-packages/yaml/constructor.py", line 570, in set_python_instance_state
    setattr(object, key, value)
TypeError: can't set attributes of built-in/extension type 'object'
```

The exception was throwed from [#L570](https://github.com/yaml/pyyaml/blob/ccc40f3e2ba384858c0d32263ac3e3a6626ab15e/lib3/yaml/constructor.py#L570)

https://github.com/yaml/pyyaml/blob/ccc40f3e2ba384858c0d32263ac3e3a6626ab15e/lib3/yaml/constructor.py#L558-L570

I think `object` should be `instance`.

### CODE REVIEW

**Comment by Hanaasagi** [comment]
resolves #232

**Comment by Hanaasagi** [comment]
This PR has been open for a week. Can I get a review? @ingydotnet

**Comment by Hanaasagi** [comment]
ping @perlpunk

**Comment by perlpunk** [comment]
Sorry, I don't know enough python yet, so I don't know about slots. @nitzmahone maybe?

**Comment by MRigal** [comment]
Very valid fix and proper tests! However, it is just a minimal update to the already exising PR https://github.com/yaml/pyyaml/pull/161/ which you could have mentioned.

@perlpunk This is definitely good code and a problem since a while!

**Comment by Hanaasagi** [comment]
May I get a review @nitzmahone

**Comment by perlpunk** [comment]
Thanks! I'll try to look at it this weekend...

**Comment by perlpunk** [comment]
I added #161 to release/5.3

**Comment by perlpunk** [comment]
released https://pypi.org/project/PyYAML/5.3/

**Pull request closed without merging**
