### PR TITLE
Drop support for Python 2.5

### PR DESCRIPTION
**Pull request by hugovk**
Closes https://github.com/yaml/pyyaml/issues/47.

### CODE REVIEW

**Comment by hugovk** [comment]
The CI failure is an unrelated problem on Python 2.6 that also affects latest master builds.

**Comment by hugovk** [comment]
Here's the pip installs for pyyaml from PyPI for the last month -- nothing for Python 2.5:
```
$ pypinfo --percent --pip pyyaml pyversion
python_version percent download_count
-------------- ------- --------------
2.7              89.4%     11,732,683
3.5               3.6%        470,139
3.6               3.3%        430,133
3.4               2.7%        351,614
2.6               1.0%        127,184
3.3               0.1%          7,931
3.7               0.0%          3,638
3.2               0.0%            284
None              0.0%            126
3.1               0.0%              2
2.8               0.0%              2

```

**Comment by hugovk** [comment]
@sigmavirus24 Any thoughts on this PR? Thanks!

**Comment by hugovk** [comment]
Merged master in and the CI now passes.

**Comment by hugovk** [comment]
Updated to resolve conflicts.

**Comment by perlpunk** [comment]
Thanks! It seems everything in this PR was patched by other PRs. Closing

**Comment by hugovk** [comment]
Great! I think https://github.com/yaml/pyyaml/issues/47 can be closed now.

**Pull request closed without merging**
