### PR TITLE
Added flag to ignore aliases/anchors

### LINKED ISSUE #103: Disable Aliases/Anchors
# Expected Behaviour
- Ability to disable generated aliases and anchors (AA) in `yaml.dump()`

# Use Case
- Tool for generating default `yaml` config file for an application
- Users of the generated config file should not need to know how AA work

# Actual Behaviour
- No option to disable AA

# Current Workaround
```python
class NoAliasDumper(yaml.Dumper):
    def ignore_aliases(self, data):
        return True

yaml.dump(x, Dumper=NoAliasDumper)
```

# Potential Solution
- Add a flag to `yaml.dump()` that switches the functionality of `ignore_aliases()`

### PR DESCRIPTION
**Pull request by nnadeau**
- Fixes #103

### CODE REVIEW

**Comment by nnadeau** [comment]
Only Python 2.6 fails, but it's EOL.

**Comment by nnadeau** [comment]
This PR will depend on https://github.com/yaml/pyyaml/pull/105

**Comment by perlpunk** [comment]
I think this can be useful.
However, when using with cyclic references, we run into an endless loop. This is a problem with the existing code, so adding this flag doesn't introduce this problem, but makes it easy to reproduce:
```
import yaml

string = "&node [ a, b, *node ]"
data = yaml.load(string)
print(data)
out = yaml.dump(data, ignore_aliases=True)
print(out)

...
RecursionError: maximum recursion depth exceeded while calling a Python object
```
The code in `represent_data` should remember the nodes it has already visited and output `null` in that case.

I might have some time to fix this, but not sure when.

**Comment by perlpunk** [comment]
On the other hand, if the desired behaviour is to expand all aliases, then we'd have to live with the possibility of an endless loop. The documentation should warn about this then.

**Comment by nnadeau** [comment]
Yes, my intention is to have no aliases at all, simplifying the YAML markup.

**Comment by nnadeau** [comment]
closing stale PR

**Pull request closed without merging**
