### PR TITLE
Force cython when building sdist

### LINKED ISSUE #182: ext/_yaml.c is missing in 4.1 tarball
Installing `pyyaml 3.12` without `cython` do build the `_yaml` extension, but installing `4.1` do not:

```
python -m venv venv3.12
./venv3.12/bin/pip install pyyaml==3.12

python -m venv venv4.1
./venv4.1/bin/pip install pyyaml==4.1

find . -name '_yaml*'
./venv3.12/lib/python3.6/site-packages/_yaml.cpython-36m-x86_64-linux-gnu.so
```

The problem is that in https://pypi.org/simple/pyyaml/ `PyYAML-3.12.tar.gz` contains `ext/_yaml.c`, but `PyYAML-4.1.tar.gz` do not, so `cython` is required for `4.1` to build the extension. (`.pyx` -> `.c`)

(question also asked in #179 but the issue was about another problem and is closed)

Could it be possible to make a new `4.1` tarball including `ext/_yaml.c`?

### PR DESCRIPTION
**Pull request by perlpunk**
Fixes #182

thanks @asottile

Alternatively there's #33 which will only issue a warning

### CODE REVIEW

**Comment by asottile** [comment]
@nitzmahone this error will only happen for packagers and not for normal users during install. `setup.py sdist` isn't part of the install pathway (`setup.py install` / `setup.py bdist_wheel`) 

If you want to convince yourself, check out this branch, build the sdist with `python setup.py sdist` and then install it in a fresh virtualenv via `pip install path/to/pyyaml.tar.gz`

**Comment by perlpunk** [comment]
I think @nitzmahone mean the warning, not the error.
I included it because the comment in #33 suggested that it would be a good idea.
We can remove it if it doesn't make sense.

**Comment by asottile** [comment]
ah! I should learn to read more carefully :)

yeah the warning probably isn't necessary given we'll have the `.c` file now 🤷‍♂️

**Comment by perlpunk** [comment]
I created #196

**Pull request closed without merging**
