### PR TITLE
Add cibuildwheel support for aarch64.

### PR DESCRIPTION
**Pull request by odidev**
Added cibuildwheel support for aarch64.
Related to #415 . @nitzmahone  please review the changes.

### CODE REVIEW

**Comment by odidev** [comment]
@nitzmahone, could you please review this PR? Thanks.

**Comment by nitzmahone** [comment]
Haven't forgotten, just been buried the past couple weeks- will try to get a look this week.

**Comment by nitzmahone** [comment]
Finally got around to looking at this: sorry, duplicate unmatrixed job using an arbitrary system-packaged libyaml doesn't really work for all the things we need to be able to do (packaging with a specific libyaml build), so I just went and did it in https://github.com/yaml/pyyaml/pull/504 for aarch64 and s390x. Not sure yet if we'll backport it to 5.x or hold for 6.0; will have to see what @ingydotnet thinks about how long 6.0 will be.

**Comment by nitzmahone** [comment]
@odidev: I talked this over with Ingy, and we're probably going to release the aarch64 and s390x wheels for the existing 5.4.1- would you be willing to try out an aarch64 wheel from the artifact archive on https://github.com/yaml/pyyaml/actions/runs/626424844 to make sure it works for you? If so, I'll go ahead and upload the missing ones for 5.4.1 to PyPI. Thanks!

**Comment by odidev** [comment]
Hi @nitzmahone, I was successfully able to install the aarch64 wheels provided by you. Please have a look at the logs:
>root@065039e88e9f:/home# pip3 --version
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
root@065039e88e9f:/home# pip3 install PyYAML-5.4.1-cp38-cp38-manylinux2014_aarch64.whl
Processing ./PyYAML-5.4.1-cp38-cp38-manylinux2014_aarch64.whl
Installing collected packages: PyYAML
Successfully installed PyYAML-5.4.1


I also executed the tests after the installation and all the test cased are passing successfully:

>`<snip/>`
===========================================================================
TESTS: 2614
_______________________________________________________________________________ summary ________________________________________________________________________________
  py38: commands succeeded
  congratulations :)
root@065039e88e9f:/home/pyyaml# uname -m
aarch64
root@065039e88e9f:/home/pyyaml#

So everything looks good to me, we can go ahead with the release.

**Comment by nitzmahone** [comment]
Thanks @odidev !

**Pull request closed without merging**
