### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**

### CODE REVIEW

**Comment by kianmeng** [comment]
@nitzmahone Should I resolve the conflict and re-submit the PR again?

**Comment by ingydotnet** [comment]
Hi @kianmeng 

Can you base the PR against the `release/6.1` branch rather than `master`?

I added the PR to https://github.com/orgs/yaml/projects/4/

**Comment by kianmeng** [comment]
@ingydotnet Done.

**Comment by ingydotnet** [comment]
Thanks.

**Comment by kianmeng** [comment]
:tada: :tada: :tada: :tada: :tada:

**Pull request merged**
